// Generated by CoffeeScript 1.3.1
(function() {

  $(document).ready(function() {
    var overLay, overModel;
    overModel = {
      color: 'black',
      opacity: '0.5',
      top: $(document).scrollTop()
    };
    overLay = ich.overLay(overModel.toJSON());
    console.log(overLay);
    $('body').append(overLay);
    return alert('WTF');
  });

}).call(this);
