// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  $(document).ready(function() {
    var SobsPin, SobsPinView, SobsPins;
    SobsPin = (function(_super) {

      __extends(SobsPin, _super);

      SobsPin.name = 'SobsPin';

      function SobsPin() {
        return SobsPin.__super__.constructor.apply(this, arguments);
      }

      return SobsPin;

    })(Backbone.Model);
    SobsPins = (function(_super) {

      __extends(SobsPins, _super);

      SobsPins.name = 'SobsPins';

      function SobsPins() {
        return SobsPins.__super__.constructor.apply(this, arguments);
      }

      SobsPins.prototype.model = SobsPin;

      return SobsPins;

    })(Backbone.Collection);
    SobsPinView = (function(_super) {

      __extends(SobsPinView, _super);

      SobsPinView.name = 'SobsPinView';

      function SobsPinView() {
        return SobsPinView.__super__.constructor.apply(this, arguments);
      }

      SobsPinView.prototype.el = $('#overlay');

      SobsPinView.prototype.initialize = function() {
        _.bindAll(this);
        return this.render();
      };

      SobsPinView.prototype.render = function() {
        var imgSquareTemplate;
        imgSquareTemplate = ich.imgPinSquare(this.model.toJSON());
        $(this.el).append(imgSquareTemplate);
        return this;
      };

      SobsPinView.prototype.pinMe = function() {
        return alert('PIN ME!');
      };

      SobsPinView.drawOverlay = function() {
        var overLay, overModel;
        overModel = {
          color: 'black',
          opacity: '0.5',
          top: $(document).scrollTop()
        };
        overLay = ich.overLay(overModel.toJSON());
        console.log(overLay);
        return $('body').append(overLay);
      };

      SobsPinView.prototype.events = {
        'click button': 'pinMe'
      };

      return SobsPinView;

    })(Backbone.View);
    return $('.separator > a').each(function() {
      var pinView, sobsPin;
      sobsPin = new SobsPin({
        escapedUrl: encodeURIComponent(this.href),
        imgUrl: this.href,
        altText: "Alt Text Coming Soon!",
        postUrl: "www.quietlikehorses.com"
      });
      return pinView = new SobsPinView({
        model: sobsPin
      });
    });
  });

}).call(this);
