// Generated by CoffeeScript 1.6.3
(function() {
  window.SobsPinsApp = {};

  (function() {
    var pins;
    SobsPinsApp.SobsPin = Backbone.Model.extend({
      sizeImage: function(width, height, newWidth) {
        var newHeight, ratio;
        ratio = height / width;
        return newHeight = ratio * newWidth;
      }
    });
    SobsPinsApp.ImgPinView = Backbone.View.extend({
      render: function() {
        var context, source, template;
        source = $('#pinterestQLHImg').html();
        template = Handlebars.compile(source);
        context = this.model.toJSON();
        $(this.el).html(template(context));
        return this;
      }
    });
    pins = [];
    return SobsPinsApp.fetchPins = function() {
      return $('.separator > a').each(function() {
        var sobsPin;
        sobsPin = new SobsPinsApp.SobsPin({
          escapedUrl: encodeURIComponent(this.href),
          imgUrl: this.href,
          altText: "Alt Text Coming Soon!",
          postUrl: "www.quietlikehorses.com",
          height: $(this).children('img').height(),
          width: $(this).children('img').width()
        });
        console.log(sobsPin.toJSON());
        return new SobsPinsApp.ImgPinView({
          el: $(this),
          model: sobsPin
        }).render();
      });
    };
  })();

  $(document).ready(function() {
    return SobsPinsApp.fetchPins();
  });

}).call(this);
