// Generated by CoffeeScript 1.6.3
(function() {
  window.SobsPinsApp = {};

  (function() {
    var pins;
    SobsPinsApp.SobsPin = Backbone.Model.extend({
      sizeImage: function(width, height, newWidth) {
        var newHeight, ratio;
        ratio = height / width;
        return newHeight = ratio * newWidth;
      },
      pinterestLinkify: function() {
        return "http://pinterest.com/pin/create/button/?url=" + (this.get('postUrl')) + "&media=" + (this.get('escapedUrl')) + "&description=" + (this.get('read quietlikehorses.com!'));
      }
    });
    SobsPinsApp.ImgPinView = Backbone.View.extend({
      render: function() {
        var context, source, template;
        source = $('#pinterestQLHImg').html();
        template = Handlebars.compile(source);
        context = this.model.toJSON();
        $(this.el).html('');
        $(this.el).html(template(context));
        this.delegateEvents();
        return this;
      },
      events: {
        "hover": "pinMe",
        "click .pinMeBttn": "pinMe"
      },
      pinMe: function() {
        var pinterestLink;
        pinterestLink = this.model.pinterestLinkify();
        window.open(this.model.pinterestLinkify());
        return false;
      }
    });
    pins = [];
    return SobsPinsApp.fetchPins = function() {
      return $('.separator > a').each(function() {
        var sobsPin;
        console.log(this.href);
        sobsPin = new SobsPinsApp.SobsPin({
          escapedUrl: encodeURIComponent(this.href),
          imgUrl: this.href,
          altText: "Alt Text Coming Soon!",
          postUrl: "www.quietlikehorses.com",
          height: $(this).children('img').height(),
          width: $(this).children('img').width()
        });
        console.log(sobsPin.toJSON());
        return new SobsPinsApp.ImgPinView({
          el: $(this),
          model: sobsPin
        }).render();
      });
    };
  })();

  $(document).ready(function() {
    return SobsPinsApp.fetchPins();
  });

}).call(this);
